### ISSUE TITLE
Make requests session reuse optional

### ISSUE THREAD

**Issue by paullesiak** [datacenter/cobra#28]
A recent change made to cobra enables requests session re-use by default. This has a dramatic improvement to performance, when making multiple sequential http requests to APIC.

However, there is a downside. If a single session object is established, and that session is accessed by multiple threads (say one thread is spun off to perform session refreshing on a regular basis, and the other is the main thread making changes), the state of the underlying SSL socket layer becomes desynchronized and will ultimately cause an SSL exception:

Error: [('SSL routines', 'SSL3_GET_RECORD', 'decryption failed or bad record mac')]

This seems to only have implications when using multiprocessing or threads in python.

One way to work around this is to kick off a separate loginsession for each thread, however does not address the use case mentioned above (login refresh).

The other workaround this is to simply disable session re-use. This issue is to track the ability to pass a parameter to a login session to disable session re-use

**Comment by rchamarthy** [comment]
We should not try to support thread safety directly in the library. The core of the library is not thread-safe by design. If thread are required, each MoDir object must be externally synchronized by the application. If this becomes a common use case we can later provide a synchronization utility. Passing thread safety information via variables is error prone and must be avoided. Clear documentation about thread safety and additional helper classes if required is the best way to address this issue.
