### ISSUE TITLE
Add support to configRequest to bundle/breakup the requests based on size

### ISSUE THREAD

**Issue by mtimm** [datacenter/cobra#58]
This might be something we wrap into the configRequestHelper(), if we can think of a good way to do it... Let people keep adding Mo's into it. As someone calls addMo to a configRequestHelper(), we calculate the length of the Object as JSON or XML, as well as get the contextRoot, and store the Mo, Length and ContextRoot in a tuple. Then within the breaking up of distributed requests, when we find a set of Mos with a common contextRoot, we combine the entire pre-calculated length of those, to see if they require more than one transaction, and break them up accordingly.

**Comment by rchamarthy** [comment]
Why is this required?I do not expect the config to be so big that we have to actually chunk it. Supporting multiple transactions in the same config request can be done but error handling scenarios will get too complicated. For now its best to leave these to the application.

**Comment by paullesiak** [comment]
This is a good idea... adding a helper to allow someone to be able to bulk together large configuration requests, and then have a helper interface to split them into the individual configRequests would be a huge time saver, and save the user from needing to understand the intricacies of sharding, context root, post limit size, etc. 

Its perfectly possible for configs to be large enough that they would require chunking. For one customer we provided a bulk provisioning script, creating static path attach to hundreds/thousands of EPGs created across many leaves. 

An ideal implementation will not provide an interface where you simply provide all configuration in a single chunk and the helper submits it all, but rather it provides back the broken down configrequest objects, so that way the user can be responsible for error handling (whether to rollback, or continue if a commit fails), yet they are still able to be freed of worrying about the underlying system limitations.

**Comment by mtimm** [comment]
Discussed this with Ravi and the situation is similar to #57.  The failure scenario's that would have to be covered potentially increase the complexity of the solution significantly.  Leaving it to the application allows the application to define how to handle those failure scenario's.  Also the example given can just as easily be done on a single MO basis.  It certainly used to be very slow but now with each session only doing one three way handshake the performance should be significantly improved.

Closing this for now but it can certainly be reopened if a balance can be found or the backend changes in a way that this becomes easier to implement.
